version: 2

updates:
  # Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    target-branch: "main"
    schedule:
      interval: "weekly"
    groups:
      "GitHub Actions":
        patterns:
          - "*" # All actions

  # Dependencies
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "main"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      "Features and patches":
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"