# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [
      "master",
      "feature/**",
      "fix/**",
      "refactor/**"
    ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node:
          - version: 16
          - version: 18
          - version: 20
          - version: 22
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: patch node gyp on windows to support Visual Studio 2019
      shell: powershell
      run: |
        pip install setuptools
        npm install --global node-gyp@9.4.1
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
    - name: Install dependencies
      run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Test typings
      run: npm run test-ts
